# Gradle settings
org.gradle.jvmargs=-Xms512m -Xmx1024m
org.gradle.daemon=false
org.gradle.logging.level=info

# Plugin versions:
springBootPluginVersion=3.3.2
dependencyManagementPluginVersion=1.1.7

# Dependency versions:
springBootVersion=3.3.2
seleniumVersion=4.23.0
jjwtVersion=0.12.6
commonsCsvVersion=1.11.0
